use_frameworks!
source = 'https://github.com/ReactiveX/RxSwift.git'


platform :ios, '10.0'

target 'ExtensionCollection_Example' do
  pod 'ExtensionCollection', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'ExtensionCollection_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
