use_frameworks!

platform :ios, '10.0'

target 'ExtensionCollection_Example' do
  pod 'ExtensionCollection', :path => '../'

  target 'ExtensionCollection_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
